version: '3.7'
services:
  db:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=IamStasy1128!
      - MYSQL_DATABASE=notesapp
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql


  backend:
    container_name: backend-for-dockerpractice
    image: stasy
    depends_on:
      - db
    ports:
      - '8080:8080'

volumes:
  db:
